"""empty message

Revision ID: 86d3ffda6fa4
Revises: d1ca124cf549
Create Date: 2025-02-07 19:20:10.654147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d3ffda6fa4'
down_revision: Union[str, None] = 'd1ca124cf549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workers2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('compensation', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workload', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('worker_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workers2_pkey')
    )
    # ### end Alembic commands ###
